[package]
name = "lib-wc"
version = "0.1.3"
edition = "2021"
readme = "README.md"
description = "cool stuff"
exclude = ["/benches", "/.github", "/fuzz"]
repository = "https://github.com/wcygan/lib-wc"
homepage = "https://github.com/wcygan/lib-wc"
license = "MPL-2.0"

[dependencies]
atomic-wait = "1.0.1"

[dev-dependencies]
criterion = "0.4.0"
quickcheck = "1"
quickcheck_macros = "1"
rand_chacha = "0.3.1"
rand_core = "0.6.4"
rand = "0.8.5"

[[bench]]
name = "lib-wc_bench"
path = "benches/lib.rs"
harness = false