[package]
name = "lib-wc"
version = "0.1.0"
edition = "2021"
readme = "README.md"
description = "cool stuff"
repository = "https://github.com/wcygan/lib-wc"
homepage = "https://github.com/wcygan/lib-wc"
license = "MPL-2.0"

[dependencies]
