[package]
name = "lib-wc"
version = "0.1.1"
edition = "2021"
readme = "README.md"
description = "cool stuff"
repository = "https://github.com/wcygan/lib-wc"
homepage = "https://github.com/wcygan/lib-wc"
license = "MPL-2.0"

[dependencies]
atomic-wait = "1.0.1"

[dev-dependencies]
criterion = "0.4.0"

[[bench]]
name = "lib-wc_bench"
path = "benches/lib.rs"
harness = false