[package]
name = "actix-hello-world"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.13.0"
actix-broker = "0.4.3"
tokio = { version = "1.23.0", features = ["full"] }